import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * AddRewardSystem — the Personal Loan reward program's data model.
 *
 * `reward_configs` is keyed by loan category (only a `'personal'` row
 * exists today) rather than being a single global row, so a future
 * category getting its own reward program is a data change, not a
 * schema change. `reward_percent` is the admin-configurable "up to X%"
 * figure; `PATCH /v1/rewards/config` (admin/employee-only) is the only
 * way to change it — no admin-panel UI ships with this migration, but
 * the endpoint is real and role-guarded today.
 *
 * `rewards` has exactly one intentional gap: nothing in this codebase
 * creates a row in it yet. A reward is only ever generated by
 * `RewardsService.generateForDisbursedLoan`, which nothing currently
 * calls — because no disbursement workflow exists yet (`LoanEntity`
 * rows are created on approval but never transition to `ACTIVE`/get
 * `disbursedAt` set). That is deliberate, not a missing wire-up: "no
 * reward before disbursement" is enforced by there being no code path
 * that can create one before that fact is real.
 */
export class AddRewardSystem1783773800000 implements MigrationInterface {
  name = 'AddRewardSystem1783773800000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "reward_configs" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "category_id" varchar(64) NOT NULL,
        "reward_percent" numeric(5,2) NOT NULL,
        "is_active" boolean NOT NULL DEFAULT true,
        "customer_message" text NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "pk_reward_configs" PRIMARY KEY ("id"),
        CONSTRAINT "uq_reward_configs_category_id" UNIQUE ("category_id")
      )
    `);

    await queryRunner.query(`
      CREATE TYPE "reward_status_enum" AS ENUM ('accrued', 'paid', 'cancelled')
    `);

    await queryRunner.query(`
      CREATE TABLE "rewards" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "loan_id" uuid NOT NULL,
        "customer_id" uuid NOT NULL,
        "category_id" varchar(64) NOT NULL,
        "principal_amount" numeric(14,2) NOT NULL,
        "reward_percent" numeric(5,2) NOT NULL,
        "reward_amount" numeric(14,2) NOT NULL,
        "status" "reward_status_enum" NOT NULL DEFAULT 'accrued',
        "disbursed_at" timestamptz NOT NULL,
        "paid_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        CONSTRAINT "pk_rewards" PRIMARY KEY ("id"),
        CONSTRAINT "uq_rewards_loan_id" UNIQUE ("loan_id"),
        CONSTRAINT "fk_rewards_loan" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE RESTRICT,
        CONSTRAINT "fk_rewards_customer" FOREIGN KEY ("customer_id") REFERENCES "users"("id") ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_rewards_customer" ON "rewards" ("customer_id")`);

    await queryRunner.query(`
      INSERT INTO "reward_configs" ("category_id", "reward_percent", "is_active", "customer_message")
      VALUES ('personal', 1.00, true, 'Earn Rewards Up To 1% on eligible Personal Loan disbursements.')
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX "idx_rewards_customer"`);
    await queryRunner.query(`DROP TABLE "rewards"`);
    await queryRunner.query(`DROP TYPE "reward_status_enum"`);
    await queryRunner.query(`DROP TABLE "reward_configs"`);
  }
}
